const tintColorLight = '#0A84FF';
const tintColorDark = '#0A84FF';

export default {
  light: {
    text: '#000000',
    textSecondary: '#666666',
    background: '#FFFFFF',
    tint: tintColorLight,
    tintTransparent: 'rgba(10, 132, 255, 0.2)',
    tabIconDefault: '#CCCCCC',
    tabIconSelected: tintColorLight,
    userBubble: '#0A84FF',
    userBubbleText: '#FFFFFF',
    aiBubble: '#F2F2F7',
    aiBubbleText: '#000000',
    inputBackground: '#F2F2F7',
    border: 'rgba(0, 0, 0, 0.1)',
    sidebarBackground: '#FFFFFF',
    danger: '#DC2626',
    dangerBackground: '#FEE2E2',
  },
  dark: {
    text: '#FFFFFF',
    textSecondary: '#A0A0A0',
    background: '#000000',
    tint: tintColorDark,
    tintTransparent: 'rgba(10, 132, 255, 0.2)',
    tabIconDefault: '#666666',
    tabIconSelected: tintColorDark,
    userBubble: '#0A84FF',
    userBubbleText: '#FFFFFF',
    aiBubble: '#1C1C1E',
    aiBubbleText: '#FFFFFF',
    inputBackground: '#1C1C1E',
    border: 'rgba(255, 255, 255, 0.1)',
    sidebarBackground: '#1C1C1E',
    danger: '#EF4444',
    dangerBackground: '#3A1C1C',
  },
};